### ISSUE TITLE
Not published on rubygems

### ISSUE THREAD

**Issue by dkniffin** [ryanhertz/ndbc#1]
I was hoping to use this gem for a project I'm working on, and probably contribute back to it. I just tried including it, and noticed that it's not published on rubygems.org: https://rubygems.org/search?utf8=%E2%9C%93&query=ndbc

**Comment by ryanhertz** [comment]
Hi @dkniffin, thanks for your interest. I've added it to rubygems.org - https://rubygems.org/gems/ndbc. Can you tell me anything about the project you are working on?

**Comment by dkniffin** [comment]
Yea. We're working on writing a new backend for an app called crnt (pronounced current). If you search "crnt surf" in the apple app store, or the android play store, it should come up.
